[server]
  name = "auth.goshop.local"
  [server.run]
    pid_file = "/tmp/tableflip.pid"
    graceful_timeout = "5s"
    health_wait = "1s"
  [server.tls]
    acme = "https://acme-staging-v02.api.letsencrypt.org/directory"
    key = "${TLS_KEY_FILE:-../../key.pem}"
    cert = "${TLS_CERT_FILE:-../../cert.pem}"
    caroot = "${TLS_CAROOT_FILE:-../../caroot.pem}"
  [server.http]
    port = 8443
    insecure_port = 8080
    enable_insecure = true
    mtls_only = false
    read_timeout = "1s"
    read_header_timeout = "2s"
    write_timeout = "1s"
    idle_timeout = "30s"
